### ISSUE TITLE
Sick

### ISSUE THREAD

**Issue by Lumphie** [Lumphie/Research_phylogenies#10]
Hey @Richelbilderbeek

I'm still sick (I got a really massive headache since monday evening (well actually since friday evening but it was gone on monday))

Not able to make it for our meeting.

**Comment by richelbilderbeek** [comment]
Okidokie, get well soon! 

It is a good idea you report this by email to [our beloved secretary](http://www.rug.nl/staff/i.c.jansen/).

**Comment by richelbilderbeek** [comment]
Happy to see you're healthy again...
