### ISSUE TITLE
Put report in editable form here

### ISSUE THREAD

**Issue by richelbilderbeek** [Lumphie/Research_phylogenies#13]
You can even just use `.md` here (I can convert it to `PDF` or `ODT` for you). 

This allows for:

 * You seeing what I've changed
 * Me seeing how you respond to feedback, which is needed for your portfolio

Feel free to reject this suggestion, but it will be (only a little bit) harder to help you getting a higher grade.

If you request it, I can give you a private repository to work in (only we or the team will have access to it).

**Comment by Lumphie** [comment]
Done (without pictures, will add them later)
