### ISSUE TITLE
Transfer ownership to @Lumphie

### ISSUE THREAD

**Issue by richelbilderbeek** [Lumphie/Research_phylogenies#4]
If @Lumphie is ready, as after the transfer, he will have to:
- [x] Create a Travis CI account (free and easy)
- [x] Activate the GitHub in Travis CI (easy)
- [x] Replace all `richelbilderbeek` by `Lumphie` (I think one replace in `README.md` is enough, Travis will tell us otherwise)

So, if you are ready, let me know :sunglasses:

**Comment by Lumphie** [comment]
Ik heb mijn BlackJack (OCLint klaagt niet meer!) al door travis gehaald (daar had ik een travis account voor nodig), dus 2 stappen heb ik al gedaan. Zal die laatste nu gaan doen!

**Comment by Lumphie** [comment]
Klein probleem: ik weet niet hoe.

**Comment by richelbilderbeek** [comment]
Ownership has been transferred. 

`README.md` can be edited from GitHub or with any text editor (it is a plain text file)
